version: '3.8'

services:
  bmps-core:
    build:
      context: .
      dockerfile: Dockerfile
    image: bmps-core:latest
    container_name: bmps-core
    ports:
      # REST API port
      - "${BMPS_PORT:-8081}:${BMPS_PORT:-8081}"
    environment:
      # Application configuration
      - BMPS_PORT=${BMPS_PORT:-8081}
      - BMPS_READ_ONLY_MODE=${BMPS_READ_ONLY_MODE:-false}
      
      # Data source API keys (required)
      - DATABENTO_KEY=${DATABENTO_KEY}
      
      # Tradovate broker credentials (if using TradovateBroker)
      - TRADOVATE_PASS=${TRADOVATE_PASS:-}
      - TRADOVATE_KEY=${TRADOVATE_KEY:-}
      - TRADOVATE_DEVICE=${TRADOVATE_DEVICE:-}
    volumes:
      # Mount custom application.conf if needed
      - ./core/src/main/resources/application.conf:/app/application.conf:ro
      
      # Optional: Mount data directory for parquet files
      # - ./data:/app/data:ro
    networks:
      - bmps-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BMPS_PORT:-8081}/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bmps-network:
    driver: bridge

# Optional: Add volumes for persistent data if needed
# volumes:
#   bmps-data:
