# BMPS Model Configuration

data:
  data_dir: "data"
  feature_dim: 22  # New ATR-normalized features from MarketFeaturesService
  label_dim: 5    # New regression labels for 1,2,5,10,20 minute horizons
  validation_split: 0.2
  random_seed: 42

model:
  # XGBoost parameters for multi-target regression/classification
  n_estimators: 1000
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.1
  reg_lambda: 1.0
  random_state: 42
  n_jobs: -1
  
  # Multi-target strategy
  strategy: "independent"  # Train separate model for each target
  
  # Calibration not applicable for regression
  calibration: false

training:
  early_stopping_rounds: 50
  eval_metric: "rmse"  # Root Mean Squared Error for regression
  verbose: 100
  min_variance_threshold: 1e-6  # Minimum variance required for training
  
prediction:
  # Thresholds for regression predictions (in ATR units)
  strong_signal_threshold: 1.0   # Strong directional signal
  weak_signal_threshold: 0.5     # Weak directional signal
  # Return predictions for all 5 time horizons
  return_all_horizons: true

paths:
  model_dir: "models"
  log_dir: "logs"